{{- define "helm-chart-common.configmap.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: env
  namespace: {{ .Values.ns }}
data:
  color: red
  env: prod
{{- end -}}
{{- define "helm-chart-common.configmap" -}}
{{- include "helm-chart-common.util.merge" (append . "helm-chart-common.configmap.tpl") -}}
{{- end -}}
