apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: {{ .Values.ns }}
spec:
  ports:
  - port: {{ .Values.nginx.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx